### ISSUE TITLE
Alert user if no features were selected

### ISSUE THREAD

**Issue by steff-o** [origo-map/multiselect-plugin#13]
When performing a select there is no indication when all layers have been queried. If there are at least one hit, the infowindow appears when all layers have been queried, but it there are not hits the InfoWindow is not displayed. This can lead to insecurity if no feature at all are selected, leaving the user wait "forever" for feedback.

Possible solutions would be:
1. A toaster message if no features were selected
2. A progress indicator. When progress is complete the user can stop waiting.
3. Pop up the infowindow with no items

Personally I would prefer a toaster, or even a modal, for tasks when it it crucial that the user gets a clear and precise answer . For instance if the task is to investigate which features are affected by something. If the answer is "none", it should be clearly stated.

**Comment by mulfvik** [comment]
Vote for .1 inside .3

**Comment by steff-o** [comment]
Also a spinner should be added.
