### ISSUE TITLE
Configurable behaviour for selection tool

### ISSUE THREAD

**Issue by jokd** [origo-map/multiselect-plugin#21]
It should be possible to change the behaviour of the selection tool when clicking items. As of now the selection tool adds new items to the selection. (Unless they already are added and `featureinfoOptions:{toggleSelectOnClick: true}` is set then they will be removed when clicked.)
Instead of adding/removing features, you may want to do a new selection by clear and select. 
Proposed solution is to either set the behaviour in the config or add a new "toggle"-button that sets how the selection tool should work.

**Comment by asemoller** [comment]
So how is this different if you add the feature in #20? Then you can add by click, buffer or any other method and with a trash button remove all the selected items without closing the infowindow, right? Isn't this the same as above with clear and select? I guess I'm missing something here 😃 

Just one thing, by default, you can just use ctrl+click on an selected item to remove it. So you don't need `featureinfoOptions:{toggleSelectOnClick: true}` to remove a selected item in the infowindow.

**Comment by jokd** [comment]
What i meant was that the tool makes a clear-and-select every time (if that is the way it is configured). Then you don't have to clear it manually. 
The toggle button would add a possibility to add to selection instead of make a new selection just like the present behaviour.

**Comment by asemoller** [comment]
Aha! Thanks for the explanation! Go for it! 😃
