### ISSUE TITLE
Toggle selection with click on feature

### ISSUE THREAD

**Issue by jokd** [origo-map/multiselect-plugin#3]
It would be nice to be able to deselect a feature by clicking on it in the map instead of in the infowindow.

**Comment by asemoller** [comment]
Use ctrl+click!

**Comment by jokd** [comment]
Would be nice to do it on touch devices as well, in some applications at least.

**Comment by jokd** [comment]
Added the toggleSelectOnClick option as an featureinfoOptions in https://github.com/origo-map/origo/pull/1028
When true, you'll add/remove feature when clicking. Can be useful when there's just a few selectable layers.

**Comment by asemoller** [comment]
@jokd - Good improvement!
